// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_specification.proto

#ifndef PROTOBUF_data_5fspecification_2eproto__INCLUDED
#define PROTOBUF_data_5fspecification_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_data_5fspecification_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsData_msg_reqImpl();
void InitDefaultsData_msg_req();
void InitDefaultsData_msg_resImpl();
void InitDefaultsData_msg_res();
inline void InitDefaults() {
  InitDefaultsData_msg_req();
  InitDefaultsData_msg_res();
}
}  // namespace protobuf_data_5fspecification_2eproto
class Data_msg_req;
class Data_msg_reqDefaultTypeInternal;
extern Data_msg_reqDefaultTypeInternal _Data_msg_req_default_instance_;
class Data_msg_res;
class Data_msg_resDefaultTypeInternal;
extern Data_msg_resDefaultTypeInternal _Data_msg_res_default_instance_;

// ===================================================================

class Data_msg_req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Data_msg_req) */ {
 public:
  Data_msg_req();
  virtual ~Data_msg_req();

  Data_msg_req(const Data_msg_req& from);

  inline Data_msg_req& operator=(const Data_msg_req& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Data_msg_req(Data_msg_req&& from) noexcept
    : Data_msg_req() {
    *this = ::std::move(from);
  }

  inline Data_msg_req& operator=(Data_msg_req&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Data_msg_req& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data_msg_req* internal_default_instance() {
    return reinterpret_cast<const Data_msg_req*>(
               &_Data_msg_req_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Data_msg_req* other);
  friend void swap(Data_msg_req& a, Data_msg_req& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Data_msg_req* New() const PROTOBUF_FINAL { return New(NULL); }

  Data_msg_req* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Data_msg_req& from);
  void MergeFrom(const Data_msg_req& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Data_msg_req* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string string_value = 1;
  void clear_string_value();
  static const int kStringValueFieldNumber = 1;
  const ::std::string& string_value() const;
  void set_string_value(const ::std::string& value);
  #if LANG_CXX11
  void set_string_value(::std::string&& value);
  #endif
  void set_string_value(const char* value);
  void set_string_value(const char* value, size_t size);
  ::std::string* mutable_string_value();
  ::std::string* release_string_value();
  void set_allocated_string_value(::std::string* string_value);

  // int32 int_value = 2;
  void clear_int_value();
  static const int kIntValueFieldNumber = 2;
  ::google::protobuf::int32 int_value() const;
  void set_int_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Data_msg_req)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr string_value_;
  ::google::protobuf::int32 int_value_;
  mutable int _cached_size_;
  friend struct ::protobuf_data_5fspecification_2eproto::TableStruct;
  friend void ::protobuf_data_5fspecification_2eproto::InitDefaultsData_msg_reqImpl();
};
// -------------------------------------------------------------------

class Data_msg_res : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Data_msg_res) */ {
 public:
  Data_msg_res();
  virtual ~Data_msg_res();

  Data_msg_res(const Data_msg_res& from);

  inline Data_msg_res& operator=(const Data_msg_res& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Data_msg_res(Data_msg_res&& from) noexcept
    : Data_msg_res() {
    *this = ::std::move(from);
  }

  inline Data_msg_res& operator=(Data_msg_res&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Data_msg_res& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data_msg_res* internal_default_instance() {
    return reinterpret_cast<const Data_msg_res*>(
               &_Data_msg_res_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Data_msg_res* other);
  friend void swap(Data_msg_res& a, Data_msg_res& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Data_msg_res* New() const PROTOBUF_FINAL { return New(NULL); }

  Data_msg_res* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Data_msg_res& from);
  void MergeFrom(const Data_msg_res& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Data_msg_res* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string status_name = 2;
  void clear_status_name();
  static const int kStatusNameFieldNumber = 2;
  const ::std::string& status_name() const;
  void set_status_name(const ::std::string& value);
  #if LANG_CXX11
  void set_status_name(::std::string&& value);
  #endif
  void set_status_name(const char* value);
  void set_status_name(const char* value, size_t size);
  ::std::string* mutable_status_name();
  ::std::string* release_status_name();
  void set_allocated_status_name(::std::string* status_name);

  // int32 status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Data_msg_res)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr status_name_;
  ::google::protobuf::int32 status_;
  mutable int _cached_size_;
  friend struct ::protobuf_data_5fspecification_2eproto::TableStruct;
  friend void ::protobuf_data_5fspecification_2eproto::InitDefaultsData_msg_resImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Data_msg_req

// string string_value = 1;
inline void Data_msg_req::clear_string_value() {
  string_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Data_msg_req::string_value() const {
  // @@protoc_insertion_point(field_get:Data_msg_req.string_value)
  return string_value_.GetNoArena();
}
inline void Data_msg_req::set_string_value(const ::std::string& value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Data_msg_req.string_value)
}
#if LANG_CXX11
inline void Data_msg_req::set_string_value(::std::string&& value) {
  
  string_value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Data_msg_req.string_value)
}
#endif
inline void Data_msg_req::set_string_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Data_msg_req.string_value)
}
inline void Data_msg_req::set_string_value(const char* value, size_t size) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Data_msg_req.string_value)
}
inline ::std::string* Data_msg_req::mutable_string_value() {
  
  // @@protoc_insertion_point(field_mutable:Data_msg_req.string_value)
  return string_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Data_msg_req::release_string_value() {
  // @@protoc_insertion_point(field_release:Data_msg_req.string_value)
  
  return string_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Data_msg_req::set_allocated_string_value(::std::string* string_value) {
  if (string_value != NULL) {
    
  } else {
    
  }
  string_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value);
  // @@protoc_insertion_point(field_set_allocated:Data_msg_req.string_value)
}

// int32 int_value = 2;
inline void Data_msg_req::clear_int_value() {
  int_value_ = 0;
}
inline ::google::protobuf::int32 Data_msg_req::int_value() const {
  // @@protoc_insertion_point(field_get:Data_msg_req.int_value)
  return int_value_;
}
inline void Data_msg_req::set_int_value(::google::protobuf::int32 value) {
  
  int_value_ = value;
  // @@protoc_insertion_point(field_set:Data_msg_req.int_value)
}

// -------------------------------------------------------------------

// Data_msg_res

// int32 status = 1;
inline void Data_msg_res::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 Data_msg_res::status() const {
  // @@protoc_insertion_point(field_get:Data_msg_res.status)
  return status_;
}
inline void Data_msg_res::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:Data_msg_res.status)
}

// string status_name = 2;
inline void Data_msg_res::clear_status_name() {
  status_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Data_msg_res::status_name() const {
  // @@protoc_insertion_point(field_get:Data_msg_res.status_name)
  return status_name_.GetNoArena();
}
inline void Data_msg_res::set_status_name(const ::std::string& value) {
  
  status_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Data_msg_res.status_name)
}
#if LANG_CXX11
inline void Data_msg_res::set_status_name(::std::string&& value) {
  
  status_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Data_msg_res.status_name)
}
#endif
inline void Data_msg_res::set_status_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  status_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Data_msg_res.status_name)
}
inline void Data_msg_res::set_status_name(const char* value, size_t size) {
  
  status_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Data_msg_res.status_name)
}
inline ::std::string* Data_msg_res::mutable_status_name() {
  
  // @@protoc_insertion_point(field_mutable:Data_msg_res.status_name)
  return status_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Data_msg_res::release_status_name() {
  // @@protoc_insertion_point(field_release:Data_msg_res.status_name)
  
  return status_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Data_msg_res::set_allocated_status_name(::std::string* status_name) {
  if (status_name != NULL) {
    
  } else {
    
  }
  status_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status_name);
  // @@protoc_insertion_point(field_set_allocated:Data_msg_res.status_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_data_5fspecification_2eproto__INCLUDED
