// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: data_specification.proto
#ifndef GRPC_data_5fspecification_2eproto__INCLUDED
#define GRPC_data_5fspecification_2eproto__INCLUDED

#include "data_specification.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class Data_Send final {
 public:
  static constexpr char const* service_full_name() {
    return "Data_Send";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status send_data(::grpc::ClientContext* context, const ::Data_msg_req& request, ::Data_msg_res* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Data_msg_res>> Asyncsend_data(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Data_msg_res>>(Asyncsend_dataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Data_msg_res>> PrepareAsyncsend_data(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Data_msg_res>>(PrepareAsyncsend_dataRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Data_msg_res>* Asyncsend_dataRaw(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Data_msg_res>* PrepareAsyncsend_dataRaw(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status send_data(::grpc::ClientContext* context, const ::Data_msg_req& request, ::Data_msg_res* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Data_msg_res>> Asyncsend_data(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Data_msg_res>>(Asyncsend_dataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Data_msg_res>> PrepareAsyncsend_data(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Data_msg_res>>(PrepareAsyncsend_dataRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::Data_msg_res>* Asyncsend_dataRaw(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Data_msg_res>* PrepareAsyncsend_dataRaw(::grpc::ClientContext* context, const ::Data_msg_req& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_send_data_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status send_data(::grpc::ServerContext* context, const ::Data_msg_req* request, ::Data_msg_res* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_send_data() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_data(::grpc::ServerContext* context, const ::Data_msg_req* request, ::Data_msg_res* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_data(::grpc::ServerContext* context, ::Data_msg_req* request, ::grpc::ServerAsyncResponseWriter< ::Data_msg_res>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_send_data<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_send_data() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_data(::grpc::ServerContext* context, const ::Data_msg_req* request, ::Data_msg_res* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_send_data : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_send_data() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::Data_msg_req, ::Data_msg_res>(std::bind(&WithStreamedUnaryMethod_send_data<BaseClass>::Streamedsend_data, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_send_data() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status send_data(::grpc::ServerContext* context, const ::Data_msg_req* request, ::Data_msg_res* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsend_data(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Data_msg_req,::Data_msg_res>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_send_data<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_send_data<Service > StreamedService;
};


#endif  // GRPC_data_5fspecification_2eproto__INCLUDED
