// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_specification.proto

#include "data_specification.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class Data_msg_reqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Data_msg_req>
      _instance;
} _Data_msg_req_default_instance_;
class Data_msg_resDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Data_msg_res>
      _instance;
} _Data_msg_res_default_instance_;
namespace protobuf_data_5fspecification_2eproto {
void InitDefaultsData_msg_reqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_Data_msg_req_default_instance_;
    new (ptr) ::Data_msg_req();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Data_msg_req::InitAsDefaultInstance();
}

void InitDefaultsData_msg_req() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsData_msg_reqImpl);
}

void InitDefaultsData_msg_resImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_Data_msg_res_default_instance_;
    new (ptr) ::Data_msg_res();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Data_msg_res::InitAsDefaultInstance();
}

void InitDefaultsData_msg_res() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsData_msg_resImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Data_msg_req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Data_msg_req, string_value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Data_msg_req, int_value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Data_msg_res, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Data_msg_res, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Data_msg_res, status_name_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Data_msg_req)},
  { 7, -1, sizeof(::Data_msg_res)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Data_msg_req_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Data_msg_res_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "data_specification.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030data_specification.proto\"7\n\014Data_msg_r"
      "eq\022\024\n\014string_value\030\001 \001(\t\022\021\n\tint_value\030\002 "
      "\001(\005\"3\n\014Data_msg_res\022\016\n\006status\030\001 \001(\005\022\023\n\013s"
      "tatus_name\030\002 \001(\t26\n\tData_Send\022)\n\tsend_da"
      "ta\022\r.Data_msg_req\032\r.Data_msg_resb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 200);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "data_specification.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_data_5fspecification_2eproto

// ===================================================================

void Data_msg_req::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Data_msg_req::kStringValueFieldNumber;
const int Data_msg_req::kIntValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Data_msg_req::Data_msg_req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_data_5fspecification_2eproto::InitDefaultsData_msg_req();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Data_msg_req)
}
Data_msg_req::Data_msg_req(const Data_msg_req& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.string_value().size() > 0) {
    string_value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.string_value_);
  }
  int_value_ = from.int_value_;
  // @@protoc_insertion_point(copy_constructor:Data_msg_req)
}

void Data_msg_req::SharedCtor() {
  string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  int_value_ = 0;
  _cached_size_ = 0;
}

Data_msg_req::~Data_msg_req() {
  // @@protoc_insertion_point(destructor:Data_msg_req)
  SharedDtor();
}

void Data_msg_req::SharedDtor() {
  string_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Data_msg_req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Data_msg_req::descriptor() {
  ::protobuf_data_5fspecification_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_5fspecification_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Data_msg_req& Data_msg_req::default_instance() {
  ::protobuf_data_5fspecification_2eproto::InitDefaultsData_msg_req();
  return *internal_default_instance();
}

Data_msg_req* Data_msg_req::New(::google::protobuf::Arena* arena) const {
  Data_msg_req* n = new Data_msg_req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Data_msg_req::Clear() {
// @@protoc_insertion_point(message_clear_start:Data_msg_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  string_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  int_value_ = 0;
  _internal_metadata_.Clear();
}

bool Data_msg_req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Data_msg_req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string string_value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->string_value().data(), static_cast<int>(this->string_value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Data_msg_req.string_value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 int_value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int_value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Data_msg_req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Data_msg_req)
  return false;
#undef DO_
}

void Data_msg_req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Data_msg_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string string_value = 1;
  if (this->string_value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string_value().data(), static_cast<int>(this->string_value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Data_msg_req.string_value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->string_value(), output);
  }

  // int32 int_value = 2;
  if (this->int_value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->int_value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Data_msg_req)
}

::google::protobuf::uint8* Data_msg_req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Data_msg_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string string_value = 1;
  if (this->string_value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string_value().data(), static_cast<int>(this->string_value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Data_msg_req.string_value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->string_value(), target);
  }

  // int32 int_value = 2;
  if (this->int_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->int_value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Data_msg_req)
  return target;
}

size_t Data_msg_req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Data_msg_req)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string string_value = 1;
  if (this->string_value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->string_value());
  }

  // int32 int_value = 2;
  if (this->int_value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->int_value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Data_msg_req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Data_msg_req)
  GOOGLE_DCHECK_NE(&from, this);
  const Data_msg_req* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Data_msg_req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Data_msg_req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Data_msg_req)
    MergeFrom(*source);
  }
}

void Data_msg_req::MergeFrom(const Data_msg_req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Data_msg_req)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.string_value().size() > 0) {

    string_value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.string_value_);
  }
  if (from.int_value() != 0) {
    set_int_value(from.int_value());
  }
}

void Data_msg_req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Data_msg_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Data_msg_req::CopyFrom(const Data_msg_req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Data_msg_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Data_msg_req::IsInitialized() const {
  return true;
}

void Data_msg_req::Swap(Data_msg_req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Data_msg_req::InternalSwap(Data_msg_req* other) {
  using std::swap;
  string_value_.Swap(&other->string_value_);
  swap(int_value_, other->int_value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Data_msg_req::GetMetadata() const {
  protobuf_data_5fspecification_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_5fspecification_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Data_msg_res::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Data_msg_res::kStatusFieldNumber;
const int Data_msg_res::kStatusNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Data_msg_res::Data_msg_res()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_data_5fspecification_2eproto::InitDefaultsData_msg_res();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Data_msg_res)
}
Data_msg_res::Data_msg_res(const Data_msg_res& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.status_name().size() > 0) {
    status_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_name_);
  }
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:Data_msg_res)
}

void Data_msg_res::SharedCtor() {
  status_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = 0;
  _cached_size_ = 0;
}

Data_msg_res::~Data_msg_res() {
  // @@protoc_insertion_point(destructor:Data_msg_res)
  SharedDtor();
}

void Data_msg_res::SharedDtor() {
  status_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Data_msg_res::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Data_msg_res::descriptor() {
  ::protobuf_data_5fspecification_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_5fspecification_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Data_msg_res& Data_msg_res::default_instance() {
  ::protobuf_data_5fspecification_2eproto::InitDefaultsData_msg_res();
  return *internal_default_instance();
}

Data_msg_res* Data_msg_res::New(::google::protobuf::Arena* arena) const {
  Data_msg_res* n = new Data_msg_res;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Data_msg_res::Clear() {
// @@protoc_insertion_point(message_clear_start:Data_msg_res)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = 0;
  _internal_metadata_.Clear();
}

bool Data_msg_res::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Data_msg_res)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string status_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_status_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->status_name().data(), static_cast<int>(this->status_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Data_msg_res.status_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Data_msg_res)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Data_msg_res)
  return false;
#undef DO_
}

void Data_msg_res::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Data_msg_res)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->status(), output);
  }

  // string status_name = 2;
  if (this->status_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status_name().data(), static_cast<int>(this->status_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Data_msg_res.status_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->status_name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Data_msg_res)
}

::google::protobuf::uint8* Data_msg_res::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Data_msg_res)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->status(), target);
  }

  // string status_name = 2;
  if (this->status_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status_name().data(), static_cast<int>(this->status_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Data_msg_res.status_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->status_name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Data_msg_res)
  return target;
}

size_t Data_msg_res::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Data_msg_res)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string status_name = 2;
  if (this->status_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->status_name());
  }

  // int32 status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Data_msg_res::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Data_msg_res)
  GOOGLE_DCHECK_NE(&from, this);
  const Data_msg_res* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Data_msg_res>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Data_msg_res)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Data_msg_res)
    MergeFrom(*source);
  }
}

void Data_msg_res::MergeFrom(const Data_msg_res& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Data_msg_res)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status_name().size() > 0) {

    status_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_name_);
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void Data_msg_res::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Data_msg_res)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Data_msg_res::CopyFrom(const Data_msg_res& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Data_msg_res)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Data_msg_res::IsInitialized() const {
  return true;
}

void Data_msg_res::Swap(Data_msg_res* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Data_msg_res::InternalSwap(Data_msg_res* other) {
  using std::swap;
  status_name_.Swap(&other->status_name_);
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Data_msg_res::GetMetadata() const {
  protobuf_data_5fspecification_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_5fspecification_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
